### PR TITLE
support for multiple members when reading.

### PR DESCRIPTION
**Pull request by argahsuknesib**

### CODE REVIEW

**Comment by argahsuknesib** [comment]
@woutslabbinck requesting for review.

**Comment by woutslabbinck** [comment]
How are your members structured in your ldp resource? As you can see, `readPage` does this already.
https://github.com/woutslabbinck/VersionAwareLDESinLDP/blob/090b10d528f47fd49ceeeabaa7dda4a2a855a2c8/src/ldes/LDESinLDP.ts#L351-L368

**Comment by woutslabbinck** [comment]
@argahsuknesib This is not necessary anymore, right?

**Comment by argahsuknesib** [comment]
@woutslabbinck yes, this is not neccessary anymore. I will close this pull request. Thanks!

**Pull request closed without merging**
